export const banksByCountry: Record<string, { code: string; name: string }[]> = {
  NG: [
    { code: '044', name: 'Access Bank' },
    { code: '023', name: 'Citibank Nigeria' },
    { code: '063', name: 'Access Bank (Diamond)' },
    { code: '050', name: 'Ecobank Nigeria' },
    { code: '070', name: 'Fidelity Bank' },
    { code: '011', name: 'First Bank of Nigeria' },
    { code: '214', name: 'First City Monument Bank' },
    { code: '058', name: 'Guaranty Trust Bank' },
    { code: '030', name: 'Heritage Bank' },
    { code: '082', name: 'Keystone Bank' },
    { code: '101', name: 'Providus Bank' },
    { code: '221', name: 'Stanbic IBTC Bank' },
    { code: '068', name: 'Standard Chartered Bank' },
    { code: '232', name: 'Sterling Bank' },
    { code: '032', name: 'Union Bank of Nigeria' },
    { code: '033', name: 'United Bank for Africa' },
    { code: '215', name: 'Unity Bank' },
    { code: '035', name: 'Wema Bank' },
    { code: '057', name: 'Zenith Bank' },
    { code: '100', name: 'Suntrust Bank' },
    { code: '102', name: 'Titan Trust Bank' },
    { code: '103', name: 'Globus Bank' },
    { code: '301', name: 'Jaiz Bank' },
    { code: '302', name: 'Taj Bank' },
    { code: '50211', name: 'Kuda Bank' },
    { code: '50515', name: 'Opay' },
    { code: '50517', name: 'Moniepoint' },
    { code: '50523', name: 'Palmpay' },
  ],
  KE: [
    { code: '01', name: 'KCB Bank Kenya' },
    { code: '02', name: 'Equity Bank' },
    { code: '03', name: 'Co-operative Bank of Kenya' },
    { code: '07', name: 'NCBA Bank Kenya' },
    { code: '09', name: 'Stanbic Bank Kenya' },
    { code: '11', name: 'Diamond Trust Bank' },
    { code: '12', name: 'Absa Bank Kenya' },
    { code: '14', name: 'I&M Bank' },
    { code: '63', name: 'Sidian Bank' },
  ],
  GH: [
    { code: '01', name: 'GCB Bank' },
    { code: '02', name: 'Absa Bank Ghana' },
    { code: '03', name: 'Standard Chartered Bank Ghana' },
    { code: '04', name: 'Ecobank Ghana' },
    { code: '05', name: 'Fidelity Bank Ghana' },
    { code: '06', name: 'Access Bank Ghana' },
    { code: '07', name: 'CalBank' },
    { code: '08', name: 'Zenith Bank Ghana' },
    { code: '09', name: 'UMB Bank' },
  ],
  ZA: [
    { code: '250655', name: 'Absa Bank' },
    { code: '051001', name: 'First National Bank' },
    { code: '025009', name: 'Standard Bank' },
    { code: '430000', name: 'Nedbank' },
    { code: '679000', name: 'Capitec Bank' },
    { code: '683000', name: 'Discovery Bank' },
    { code: '589000', name: 'TymeBank' },
  ],
  US: [
    { code: '021000021', name: 'JPMorgan Chase' },
    { code: '021000089', name: 'Bank of America' },
    { code: '021001088', name: 'Wells Fargo' },
    { code: '026009593', name: 'Citibank' },
    { code: '053000219', name: 'U.S. Bank' },
    { code: '071000013', name: 'PNC Bank' },
    { code: '211075086', name: 'Capital One' },
  ],
};